/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package assignment1-0.1.0.0 */
#ifndef VERSION_assignment1
#define VERSION_assignment1 "0.1.0.0"
#endif /* VERSION_assignment1 */
#ifndef MIN_VERSION_assignment1
#define MIN_VERSION_assignment1(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_assignment1 */

/* package base-4.12.0.0 */
#ifndef VERSION_base
#define VERSION_base "4.12.0.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  12 || \
  (major1) == 4 && (major2) == 12 && (minor) <= 0)
#endif /* MIN_VERSION_base */

/* tool gcc-4.2.1 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "4.2.1"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  2 || \
  (major1) == 4 && (major2) == 2 && (minor) <= 1)
#endif /* MIN_TOOL_VERSION_gcc */

/* tool ghc-8.6.5 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "8.6.5"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  6 || \
  (major1) == 8 && (major2) == 6 && (minor) <= 5)
#endif /* MIN_TOOL_VERSION_ghc */

/* tool ghc-pkg-8.6.5 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "8.6.5"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  6 || \
  (major1) == 8 && (major2) == 6 && (minor) <= 5)
#endif /* MIN_TOOL_VERSION_ghc_pkg */

/* tool haddock-2.22.0 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.22.0"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  22 || \
  (major1) == 2 && (major2) == 22 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_haddock */

/* tool hpc-0.67 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.67"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  67 || \
  (major1) == 0 && (major2) == 67 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */

/* tool hsc2hs-0.68.5 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.5"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 5)
#endif /* MIN_TOOL_VERSION_hsc2hs */

/* tool pkg-config-0.29.2 */
#ifndef TOOL_VERSION_pkg_config
#define TOOL_VERSION_pkg_config "0.29.2"
#endif /* TOOL_VERSION_pkg_config */
#ifndef MIN_TOOL_VERSION_pkg_config
#define MIN_TOOL_VERSION_pkg_config(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  29 || \
  (major1) == 0 && (major2) == 29 && (minor) <= 2)
#endif /* MIN_TOOL_VERSION_pkg_config */

/* tool runghc-8.6.5 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "8.6.5"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  6 || \
  (major1) == 8 && (major2) == 6 && (minor) <= 5)
#endif /* MIN_TOOL_VERSION_runghc */

#ifndef CURRENT_PACKAGE_KEY
#define CURRENT_PACKAGE_KEY "assignment1-0.1.0.0-6ENGcrQgHTUHL7sbPpRWSU"
#endif /* CURRENT_PACKAGE_KEY */
#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "assignment1-0.1.0.0-6ENGcrQgHTUHL7sbPpRWSU"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "0.1.0.0"
#endif /* CURRENT_PACKAGE_VERSION */

#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package assignment1-0.1.0.0 */
#ifndef VERSION_assignment1
#define VERSION_assignment1 "0.1.0.0"
#endif /* VERSION_assignment1 */
#ifndef MIN_VERSION_assignment1
#define MIN_VERSION_assignment1(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_assignment1 */

/* package assignment1-0.1.0.0 */
#ifndef VERSION_assignment1
#define VERSION_assignment1 "0.1.0.0"
#endif /* VERSION_assignment1 */
#ifndef MIN_VERSION_assignment1
#define MIN_VERSION_assignment1(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_assignment1 */

/* package base-4.12.0.0 */
#ifndef VERSION_base
#define VERSION_base "4.12.0.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  12 || \
  (major1) == 4 && (major2) == 12 && (minor) <= 0)
#endif /* MIN_VERSION_base */

/* package diagrams-1.4 */
#ifndef VERSION_diagrams
#define VERSION_diagrams "1.4"
#endif /* VERSION_diagrams */
#ifndef MIN_VERSION_diagrams
#define MIN_VERSION_diagrams(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  4 || \
  (major1) == 1 && (major2) == 4 && (minor) <= 0)
#endif /* MIN_VERSION_diagrams */

/* package diagrams-contrib-1.4.4 */
#ifndef VERSION_diagrams_contrib
#define VERSION_diagrams_contrib "1.4.4"
#endif /* VERSION_diagrams_contrib */
#ifndef MIN_VERSION_diagrams_contrib
#define MIN_VERSION_diagrams_contrib(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  4 || \
  (major1) == 1 && (major2) == 4 && (minor) <= 4)
#endif /* MIN_VERSION_diagrams_contrib */

/* package diagrams-lib-1.4.3 */
#ifndef VERSION_diagrams_lib
#define VERSION_diagrams_lib "1.4.3"
#endif /* VERSION_diagrams_lib */
#ifndef MIN_VERSION_diagrams_lib
#define MIN_VERSION_diagrams_lib(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  4 || \
  (major1) == 1 && (major2) == 4 && (minor) <= 3)
#endif /* MIN_VERSION_diagrams_lib */

/* package diagrams-rasterific-1.4.2 */
#ifndef VERSION_diagrams_rasterific
#define VERSION_diagrams_rasterific "1.4.2"
#endif /* VERSION_diagrams_rasterific */
#ifndef MIN_VERSION_diagrams_rasterific
#define MIN_VERSION_diagrams_rasterific(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  4 || \
  (major1) == 1 && (major2) == 4 && (minor) <= 2)
#endif /* MIN_VERSION_diagrams_rasterific */

/* package optparse-applicative-0.14.3.0 */
#ifndef VERSION_optparse_applicative
#define VERSION_optparse_applicative "0.14.3.0"
#endif /* VERSION_optparse_applicative */
#ifndef MIN_VERSION_optparse_applicative
#define MIN_VERSION_optparse_applicative(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  14 || \
  (major1) == 0 && (major2) == 14 && (minor) <= 3)
#endif /* MIN_VERSION_optparse_applicative */

/* tool gcc-4.2.1 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "4.2.1"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  2 || \
  (major1) == 4 && (major2) == 2 && (minor) <= 1)
#endif /* MIN_TOOL_VERSION_gcc */

/* tool ghc-8.6.5 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "8.6.5"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  6 || \
  (major1) == 8 && (major2) == 6 && (minor) <= 5)
#endif /* MIN_TOOL_VERSION_ghc */

/* tool ghc-pkg-8.6.5 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "8.6.5"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  6 || \
  (major1) == 8 && (major2) == 6 && (minor) <= 5)
#endif /* MIN_TOOL_VERSION_ghc_pkg */

/* tool haddock-2.22.0 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.22.0"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  22 || \
  (major1) == 2 && (major2) == 22 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_haddock */

/* tool hpc-0.67 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.67"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  67 || \
  (major1) == 0 && (major2) == 67 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */

/* tool hsc2hs-0.68.5 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.5"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 5)
#endif /* MIN_TOOL_VERSION_hsc2hs */

/* tool pkg-config-0.29.2 */
#ifndef TOOL_VERSION_pkg_config
#define TOOL_VERSION_pkg_config "0.29.2"
#endif /* TOOL_VERSION_pkg_config */
#ifndef MIN_TOOL_VERSION_pkg_config
#define MIN_TOOL_VERSION_pkg_config(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  29 || \
  (major1) == 0 && (major2) == 29 && (minor) <= 2)
#endif /* MIN_TOOL_VERSION_pkg_config */

/* tool runghc-8.6.5 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "8.6.5"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  6 || \
  (major1) == 8 && (major2) == 6 && (minor) <= 5)
#endif /* MIN_TOOL_VERSION_runghc */

#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "assignment1-0.1.0.0-EMpb9th7gZbHwLHVzvlKp-draw"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "0.1.0.0"
#endif /* CURRENT_PACKAGE_VERSION */

#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
